"""Deterministic PLAN, VERIFY, and RELEASE contracts for Project FORGE."""

from forge_core.access_control import (
    Actor,
    AuditEvent,
    AuthorizationRequest,
    AuthorizationResult,
    Membership,
    Organization,
    Permission,
    ProjectAccess,
    Role,
    authorize,
    build_audit_event,
)
from forge_core.agent_gateway import ForgeAgentGateway
from forge_core.cad_geometry import (
    CADGeometryAsset,
    STEPGeometrySummary,
    StoredCADGeometryAsset,
    parse_step_summary,
    parse_stl_asset,
)
from forge_core.cad_imports import (
    CADImportKind,
    ImportedCADAsset,
    SolidWorksExportPackage,
    import_cad_payload,
    import_solidworks_export_package,
)
from forge_core.cae_connectors import (
    AnsysUnavailableConnector,
    CAEApprovalRef,
    CAEConnectorError,
    CAEEvidenceMetadata,
    CAEReadResult,
    CAERunRef,
    CAESubmitRequest,
    MATLABProductionServerClient,
    SimScaleCAEClient,
    ansys_connector_status,
)
from forge_core.change_management import ArtifactDomain, EvidenceTier, ReleaseStatus
from forge_core.change_planning import (
    AssetInput,
    AssetInputKind,
    ChangeImpactPreview,
    ChangeScenario,
    ComponentSpecification,
    PlanIntentKind,
    PlannedComponentChange,
    PlanVerification,
)
from forge_core.connectors import ConnectorRegistry, ReadOnlyAdapterManifest
from forge_core.conversation_runtime import (
    AssistantDraft,
    CitedClaim,
    ConversationRequest,
    ConversationRuntimeService,
    ProviderManifest,
    RetrievedContextChunk,
    RuntimeDisposition,
    RuntimeResult,
    build_context_chunk,
    build_prompt_manifest,
    build_provider_manifest,
)
from forge_core.conversational_design import (
    ClaimConfidence,
    DesignCandidateSnapshot,
    DesignConversationState,
    DesignParameter,
    DesignStateTransition,
    EvidenceClaim,
    EvidenceClaimKind,
    SimulationBinding,
    SimulationMetric,
    build_design_candidate,
    build_evidence_claim,
    build_simulation_binding,
)
from forge_core.conversational_persistence import (
    StoredDesignCandidate,
    StoredDesignStateTransition,
    StoredEvidenceClaim,
    StoredSimulationBinding,
)
from forge_core.deployment_readiness import (
    DeploymentCapabilityProfile,
    DeploymentMode,
    DeploymentReadinessAssessment,
    DeploymentReadinessStatus,
    DeploymentRequirement,
    UnmetDeploymentRequirement,
    assess_deployment_readiness,
    build_deployment_profile,
)
from forge_core.evidence_runners import (
    CommandEvidenceRunner,
    EdgeEvidenceEnvelope,
    EdgeEvidenceVerifier,
    EvidenceRunRequest,
    EvidenceRunResult,
    RegisteredEvidenceCommand,
    VerifiedEdgeEvidence,
    sign_edge_evidence_hmac,
)
from forge_core.external_api_adapters import (
    ArasReadOnlyClient,
    AutodeskAPSReadOnlyClient,
    GitLabReadOnlyClient,
    JenkinsReadOnlyClient,
    OnshapeReadOnlyClient,
    WindchillReadOnlyClient,
    solidworks_3dexperience_descriptor,
    teamcenter_descriptor,
)
from forge_core.external_evidence_planning import (
    ExternalEvidencePlanVerification,
    OperatingScenario,
    RequiredExternalEvidencePlan,
    build_required_external_evidence_plan,
    verify_external_evidence_plan,
)
from forge_core.impact_engine import ChangeImpactAssessment, analyze_change
from forge_core.loopback_api import LoopbackAPI, create_loopback_server
from forge_core.models import Verdict
from forge_core.operations import (
    BackupManifest,
    DatabaseHealthReport,
    OperationalStatus,
    RestoreVerification,
    SQLiteOperationsService,
)
from forge_core.planning_persistence import (
    StoredChangeImpactPreview,
    StoredExternalEvidencePlan,
    StoredExternalEvidencePlanVerification,
    StoredPlanVerification,
)
from forge_core.preview_engine import (
    preview_change_scenario,
    verify_plan_against_actual,
)
from forge_core.release_readiness import (
    FirmwareBuildEvidence,
    ReleaseReadinessDecision,
    TestExecutionEvidence,
    evaluate_release_readiness,
)
from forge_core.release_service import ReleaseIntegrationService
from forge_core.remote_mcp import ForgeRemoteMCPTransport
from forge_core.resolution_persistence import (
    StoredDesignProposalSet,
    StoredReleaseDiagnosis,
    StoredResolutionPlan,
)
from forge_core.resolution_planning import (
    BlockerDiagnosis,
    DesignAlternative,
    DesignProposalSet,
    EngineeringGoal,
    FixProposal,
    FixProposalSet,
    ProposalSelection,
    ReplanSeed,
)
from forge_core.semantic_rag import (
    DeterministicEmbeddingProvider,
    SemanticContextChunk,
    SemanticRAGIndex,
    SemanticSearchResult,
    build_semantic_chunks,
)

__all__ = [
    "Actor",
    "AnsysUnavailableConnector",
    "ArasReadOnlyClient",
    "ArtifactDomain",
    "AuditEvent",
    "AuthorizationRequest",
    "AuthorizationResult",
    "AutodeskAPSReadOnlyClient",
    "BackupManifest",
    "CAEApprovalRef",
    "CAEConnectorError",
    "CAEEvidenceMetadata",
    "CAEReadResult",
    "CAERunRef",
    "CAESubmitRequest",
    "AssetInput",
    "AssetInputKind",
    "AssistantDraft",
    "BlockerDiagnosis",
    "CitedClaim",
    "CADGeometryAsset",
    "CADImportKind",
    "ChangeImpactPreview",
    "ChangeImpactAssessment",
    "ChangeScenario",
    "ComponentSpecification",
    "CommandEvidenceRunner",
    "ConnectorRegistry",
    "ClaimConfidence",
    "ConversationRequest",
    "ConversationRuntimeService",
    "DatabaseHealthReport",
    "DeterministicEmbeddingProvider",
    "DesignCandidateSnapshot",
    "DesignConversationState",
    "DesignParameter",
    "DesignStateTransition",
    "DesignAlternative",
    "DesignProposalSet",
    "DeploymentCapabilityProfile",
    "DeploymentMode",
    "DeploymentReadinessAssessment",
    "DeploymentReadinessStatus",
    "DeploymentRequirement",
    "EngineeringGoal",
    "EdgeEvidenceEnvelope",
    "EdgeEvidenceVerifier",
    "EvidenceClaim",
    "EvidenceClaimKind",
    "EvidenceRunRequest",
    "EvidenceRunResult",
    "EvidenceTier",
    "ExternalEvidencePlanVerification",
    "FirmwareBuildEvidence",
    "ForgeAgentGateway",
    "ForgeRemoteMCPTransport",
    "FixProposal",
    "FixProposalSet",
    "GitLabReadOnlyClient",
    "ImportedCADAsset",
    "JenkinsReadOnlyClient",
    "LoopbackAPI",
    "MATLABProductionServerClient",
    "Membership",
    "OperatingScenario",
    "OperationalStatus",
    "OnshapeReadOnlyClient",
    "Organization",
    "PlanIntentKind",
    "PlanVerification",
    "PlannedComponentChange",
    "Permission",
    "ProjectAccess",
    "ReadOnlyAdapterManifest",
    "RegisteredEvidenceCommand",
    "ProposalSelection",
    "ProviderManifest",
    "RequiredExternalEvidencePlan",
    "RetrievedContextChunk",
    "ReleaseReadinessDecision",
    "ReleaseIntegrationService",
    "ReleaseStatus",
    "ReplanSeed",
    "RestoreVerification",
    "Role",
    "RuntimeDisposition",
    "RuntimeResult",
    "STEPGeometrySummary",
    "SemanticContextChunk",
    "SemanticRAGIndex",
    "SemanticSearchResult",
    "SimulationBinding",
    "SimulationMetric",
    "SimScaleCAEClient",
    "SolidWorksExportPackage",
    "SQLiteOperationsService",
    "StoredChangeImpactPreview",
    "StoredCADGeometryAsset",
    "StoredDesignCandidate",
    "StoredDesignStateTransition",
    "StoredDesignProposalSet",
    "StoredExternalEvidencePlan",
    "StoredExternalEvidencePlanVerification",
    "StoredEvidenceClaim",
    "StoredPlanVerification",
    "StoredReleaseDiagnosis",
    "StoredResolutionPlan",
    "StoredSimulationBinding",
    "TestExecutionEvidence",
    "UnmetDeploymentRequirement",
    "Verdict",
    "VerifiedEdgeEvidence",
    "WindchillReadOnlyClient",
    "analyze_change",
    "ansys_connector_status",
    "assess_deployment_readiness",
    "authorize",
    "build_context_chunk",
    "build_deployment_profile",
    "build_required_external_evidence_plan",
    "build_design_candidate",
    "build_evidence_claim",
    "build_simulation_binding",
    "build_audit_event",
    "build_prompt_manifest",
    "build_provider_manifest",
    "build_semantic_chunks",
    "create_loopback_server",
    "evaluate_release_readiness",
    "import_cad_payload",
    "import_solidworks_export_package",
    "preview_change_scenario",
    "parse_step_summary",
    "parse_stl_asset",
    "sign_edge_evidence_hmac",
    "solidworks_3dexperience_descriptor",
    "teamcenter_descriptor",
    "verify_plan_against_actual",
    "verify_external_evidence_plan",
]
